version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm uninstall -g angular-cli @angular/cli
      - sudo npm cache clean --force
      - export NODE_OPTIONS=--openssl-legacy-provider
      - npm install -g @angular/cli@11.2.11
      - npm install --save-dev @angular/cli@11.2.11
      - rm spring-petclinic-angular/package-lock.json
      - npm install
      
  build:
    commands:
      - echo Build started on `date`
      - ng build
  post_build:
    commands:
      - echo Build completed on `date`
