version: 0.2
phases: 
  pre_build:
    commands:
      - echo logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 631692196381.dkr.ecr.eu-west-2.amazonaws.com)
      - REPOSITORY_URI=631692196381.dkr.ecr.eu-west-2.amazonaws.com/fp
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Bulding the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Doker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image defintions file...
      - printf '[{"name":"backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
